### ISSUE TITLE
ISpeciminFactory should have a max value

### ISSUE THREAD

**Issue by tomkuijsten** [kgroener/Simulation#1]
As discussed, the ISpeciminFactory should be implemented by a participating project, one of the factory methods is now:

```cs
IEnumerable<ISpecie> CreateGeneration(int size);
```

I think this should be `int maxAmount`. The player should be aware of the maximum amount of specimen he is allowed to return. As a result, the result of this method should be finished with `.Take(1000)` the make sure the player isn't "cheating". This also allows the player to create just one specimen (eg if someone decides to implement one specimen which is controlled manually).

**Comment by kgroener** [comment]
I agree.
ISpecimenFactory has been updated. Take method is used when creating a generation.
