### ISSUE TITLE
Find a better name for the project

### ISSUE THREAD

**Issue by tomkuijsten** [kgroener/Simulation#19]
Simulation is not realy catchy :)

**Comment by kgroener** [comment]
What about "Specie Architect"? 
Or something related to "Survival of the fittest"?

**Comment by tomkuijsten** [comment]
I thought a bit about "survival of the fittest"...

what about "Sparta" or "Spartans" 😀

**Comment by tomkuijsten** [comment]
We settled on "StayingAlive" :)
